### ISSUE TITLE
Create documentation for implementing workflow

### ISSUE THREAD

**Issue by jeremyf** [samvera-deprecated/curation_concerns#1033]
- [x] From a given state machine diagram, what is the resulting configuration
  - Example one https://github.com/projecthydra/curation_concerns/wiki/Defining-a-Workflow
- [ ] Document where to go for workflow configuration
  - [x] Where is the generator that installs the configuration for a workflow
  - [ ] How to write an email notification template
  - [ ] What are the callbacks that were installed and how to make adjustments

**Comment by jeremyf** [comment]
I've been working on this example https://github.com/projecthydra/curation_concerns/wiki/Defining-a-Workflow

**Comment by mjgiarlo** [comment]
@jeremyf might you be inclined to self-assign this issue and take on the unchecked tasks above in the new year?

**Comment by mjgiarlo** [comment]
@jeremyf ping re: :arrow_up:!

**Comment by jeremyf** [comment]
I'm AFK, but please assign me to this task.

Jeremy Friesen

**Comment by mjgiarlo** [comment]
Done, and I'll make sure to port these docs over to Hyrax when appropriate. Thanks, @jeremyf!
