### ISSUE TITLE
Improve documentation of the concepts introduced in /app

### ISSUE THREAD

**Issue by jeremyf** [samvera-deprecated/curation_concerns#766]
For those that have completed their Rails 101 experience, the concepts of Helper, Models, Controllers, and Views are well explained. However, CurationConcerns adds `Actors`, `Forms`, `Indexers`, `Inputs`, `Jobs`, `Presenters`, `Renderers`, `SearchBuilders`, `Services`, `Validators`.

For reference, [Sipity](//github.com//ndlib/sipity) has documentation of some of the concepts that can be visited and provide some guidance.
- [x] Actors
- [x] Forms
- [ ] Indexers
- [ ] Inputs
- [ ] Jobs
- [ ] Presenters
- [ ] Renderers
- [ ] SearchBuilders
- [ ] Services
- [ ] Validators

**Comment by escowles** [comment]
There is a Vagrant project to spin up a stock CurationConcerns app, with some accompanying instructions for customizing that covers some of this:

https://github.com/escowles/curation-concerns-vagrant/wiki/Dive-Into-Curation-Concerns

**Comment by mjgiarlo** [comment]
Unassigning this and moving back to the backlog.
